### ISSUE TITLE
리뷰유도

### ISSUE THREAD

**Issue by ebPark9511** [yapp-project/Toonie#133]
바로 띄우는것보단 사용자가 좀 익숙해졌을때 쯤에 띄우는게 좋다고 하더라구요..!
언제 띄울지도 같이 생각해보면 좋을것같아용~!!!

**Comment by ebPark9511** [comment]
https://zeddios.tistory.com/551

**Comment by Jae-eun** [comment]
내 평화로운 생각으로는 사용자가 찜한 툰 개수?로 정하면 편하지 않으까? 뭐 찜한 툰이 10개 되었다! => 리뷰 남겨보세요~ 그런식

**Comment by ebPark9511** [comment]
오 조타 근데 10개 넘많아여 5개정도 어때요?

**Comment by Jae-eun** [comment]
아 많다닝ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ그랫군 나의 순진한 원래 생각은 스무개였는뎅 그래 5갴ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ!

**Comment by eojine** [comment]
저는 찜을 그렇게 많이 안할수도 있을 것 같아서 ,,, 최근 본 목록으로 5개 어떤가용?

**Comment by Jae-eun** [comment]
아하 그런가! 조아
